"""
Django settings for titan project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bpkpomo&68$9x6#%$k_4cjw=-5-byxqt7cp78er5&fj^+v6f9j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


CORS_ORIGIN_WHITELIST = [
    'www.eheindustries.com',
    'eheindustries.com',
    'http://localhost:3000',
    'www.eheindia.com',
    'eheindia.com'
]

CORS_ALLOWED_ORIGINS = [
    "https://eheindia.com",
    "https://eheindustries.com",
    "https://www.eheindia.com",
    "https://www.eheindustries.com",
    'http://localhost:3000',
]
CORS_EXPOSE_HEADERS = ["Content-Disposition"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'lead',
    'rest_framework',
    'corsheaders',
    'authentication',
    'organization',  # Manages businesses & locations
    'account',       # Manages user profiles
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_NAME": "accessToken",
    "REFRESH_TOKEN_NAME": "refreshToken",
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

AUTH_COOKIE_SECURE = True  # Send cookie only over HTTPS
AUTH_COOKIE_HTTP_ONLY = True  # Prevent JavaScript access (security)
AUTH_COOKIE_SAMESITE = "None"  # Allow cross-site requests if needed
AUTH_COOKIE_PATH = "/"

ROOT_URLCONF = 'titan.urls'

TEMPLATES = []

WSGI_APPLICATION = 'titan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'titan_db',
		'USER':'root',
		'PASSWORD' : 'root',
		'HOST':'127.0.0.1',
		'PORT':'3307',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
