# Generated by Django 6.0.6 on 2026-06-13 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('discription', models.CharField(max_length=1000, null=True)),
                ('system_generated', models.CharField(max_length=100, null=True)),
                ('stage', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed_bucket', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(null=True)),
                ('task_date', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('active', models.BooleanField()),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('system_generated', models.CharField(max_length=100, null=True)),
                ('task_complete_description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTimelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_identifier', models.IntegerField()),
                ('activity_type', models.CharField(max_length=50)),
                ('changes', models.JSONField()),
                ('description', models.TextField(blank=True, help_text='Optional description or notes.', null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('location', models.ForeignKey(blank=True, db_column='location', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.locations')),
                ('organization', models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='Ldcntrl',
            fields=[
                ('sess_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('load_type', models.CharField(blank=True, choices=[('Bulk Import', 'Bulk Import'), ('API', 'API'), ('Manual Entry', 'Manual Entry')], max_length=50, null=True)),
                ('load_status', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('load_timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.IntegerField(null=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.locations')),
                ('organization', models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sub_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='lead.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('contact', models.CharField(max_length=1000, null=True)),
                ('valid_contact', models.CharField(max_length=1000, null=True)),
                ('lead_type', models.CharField(max_length=1000, null=True)),
                ('query', models.CharField(max_length=1000, null=True)),
                ('recieved_date', models.CharField(max_length=1000, null=True)),
                ('interested_in', models.CharField(max_length=1000, null=True)),
                ('assigned_to', models.IntegerField(null=True)),
                ('source_assigned', models.CharField(max_length=1000, null=True)),
                ('product_code', models.CharField(max_length=1000, null=True)),
                ('product_type', models.CharField(max_length=1000, null=True)),
                ('follow_up_current_status', models.CharField(max_length=1000, null=True)),
                ('source', models.CharField(max_length=1000, null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('priority', models.CharField(default='cold', max_length=10, null=True)),
                ('account', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=10, null=True)),
                ('last_updated_dt', models.DateTimeField(auto_now=True)),
                ('revenue', models.IntegerField(null=True)),
                ('brokerage', models.IntegerField(null=True)),
                ('hash_key', models.CharField(max_length=100, null=True)),
                ('golden', models.CharField(max_length=10, null=True)),
                ('sess_id', models.IntegerField(null=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.locations')),
                ('organization', models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizations')),
                ('lead_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='lead.stage')),
                ('lead_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='lead.status')),
            ],
        ),
    ]
